import { useAuth } from '../context/AuthContext';
import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import html2pdf from 'html2pdf.js';

export default function Dashboard() {
  const { user, loading } = useAuth();
  const navigate = useNavigate();
  

  const semesterStats = [
    { sem: 'Sem 1', gpa: '9.13', attendance: '96%', credits: 22, subjects: 6 },
    { sem: 'Sem 2', gpa: '9.18', attendance: '94%', credits: 22, subjects: 6 },
    { sem: 'Sem 3', gpa: '9.36', attendance: '91%', credits: 23, subjects: 6 },
    { sem: 'Sem 4', gpa: '9.55', attendance: '93%', credits: 22, subjects: 6 },
  ];

  const [selected, setSelected] = useState(semesterStats[0]);
  const [downloadSem, setDownloadSem] = useState('Sem 1');

  useEffect(() => {
    if (!loading && !user) {
      navigate('/login');
    }
  }, [user, loading, navigate]);

  const handleDownload = () => {
    const semData = semesterStats.find(s => s.sem === downloadSem);

const content = `
  <div style="font-family:Arial, sans-serif; padding: 20px;">
    <h2 style="text-align:center; margin-bottom: 30px;">${user?.name}'s Academic Report</h2>
    <table style="width:100%; border-collapse:collapse; margin-top:20px;" border="1">
      <thead>
        <tr>
          <th style="padding:8px; text-align: center;">Semester</th>
          <th style="padding:8px; text-align: center;">GPA</th>
          <th style="padding:8px; text-align: center;">Attendance</th>
          <th style="padding:8px; text-align: center;">Credits</th>
          <th style="padding:8px; text-align: center;">Subjects</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="padding:8px; text-align: center;">${semData.sem}</td>
          <td style="padding:8px; text-align: center;">${semData.gpa}</td>
          <td style="padding:8px; text-align: center;">${semData.attendance}</td>
          <td style="padding:8px; text-align: center;">${semData.credits}</td>
          <td style="padding:8px; text-align: center;">${semData.subjects}</td>
        </tr>
      </tbody>
    </table>
    <p style="text-align: center; font-size: 12px; margin-top: 30px; color: #888;">Generated by Student Portal</p>
  </div>
`;


    const opt = {
      margin: 0.5,
      filename: `${user?.name}_${downloadSem}_Report.pdf`,
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
    };

    html2pdf().from(content).set(opt).save();
  };

  if (loading) return <p className="p-4">Loading...</p>;

  return (
    <div className="min-h-screen bg-white text-black dark:bg-black dark:text-white p-6">
      {/* Header */}
      <div className="w-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white py-10 px-6 rounded-xl shadow-lg mb-10">
        <h1 className="text-3xl font-bold mb-2">Welcome back, {user?.name || 'Student'}!</h1>
        <p className="text-md">Select a semester below to view your performance.</p>
      </div>

      {/* Download Controls */}
      <div className="mb-6 flex flex-col md:flex-row md:items-center gap-4">
        <label className="font-semibold">📄 Download Report for:</label>
        <select
          value={downloadSem}
          onChange={(e) => setDownloadSem(e.target.value)}
          className="px-3 py-2 border rounded dark:bg-gray-800"
        >
          {semesterStats.map((s, i) => (
            <option key={i} value={s.sem}>
              {s.sem}
            </option>
          ))}
        </select>
        <button
          onClick={handleDownload}
          className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition"
        >
          📥 Download Report
        </button>
      </div>

      {/* Dynamic Summary Cards */}
      <div className="mb-6">
        <h2 className="text-xl font-bold mb-2">Semester: {selected.sem}</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 rounded-lg shadow-lg hover:shadow-2xl transform transition duration-300 hover:scale-105 bg-green-200 dark:bg-green-700">
            <div className="text-4xl mb-2">🎓</div>
            <h2 className="text-xl font-semibold mb-1">GPA</h2>
            <p className="text-3xl font-bold">{selected.gpa}</p>
          </div>
          <div className="p-6 rounded-lg shadow-lg hover:shadow-2xl transform transition duration-300 hover:scale-105 bg-yellow-200 dark:bg-yellow-600">
            <div className="text-4xl mb-2">📅</div>
            <h2 className="text-xl font-semibold mb-1">Attendance</h2>
            <p className="text-3xl font-bold">{selected.attendance}</p>
          </div>
          <div className="p-6 rounded-lg shadow-lg hover:shadow-2xl transform transition duration-300 hover:scale-105 bg-blue-200 dark:bg-blue-700">
            <div className="text-4xl mb-2">📘</div>
            <h2 className="text-xl font-semibold mb-1">Subjects</h2>
            <p className="text-3xl font-bold">{selected.subjects} / 6</p>
          </div>
        </div>
      </div>

      {/* Semester Table */}
      <div>
        <h2 className="text-xl font-bold mb-4">Academic Performance by Semester</h2>
        <div className="overflow-x-auto">
          <table className="min-w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg">
            <thead>
              <tr className="text-left text-sm font-semibold bg-gray-200 dark:bg-gray-700 text-black dark:text-white">
                <th className="py-3 px-4">Semester</th>
                <th className="py-3 px-4">GPA</th>
                <th className="py-3 px-4">Attendance</th>
                <th className="py-3 px-4">Credits</th>
                <th className="py-3 px-4">Subjects</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {semesterStats.map((row, i) => (
                <tr
                  key={i}
                  onClick={() => setSelected(row)}
                  className={`cursor-pointer border-b border-gray-300 dark:border-gray-600 hover:bg-indigo-100 dark:hover:bg-gray-700 transition ${
                    selected.sem === row.sem ? 'bg-indigo-50 dark:bg-gray-700' : ''
                  }`}
                >
                  <td className="py-3 px-4">{row.sem}</td>
                  <td className="py-3 px-4">{row.gpa}</td>
                  <td className="py-3 px-4">{row.attendance}</td>
                  <td className="py-3 px-4">{row.credits}</td>
                  <td className="py-3 px-4">{row.subjects}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
